---
name: build_create_release
# yamllint disable rule:line-length

on:
  workflow_dispatch:
    inputs:
      draft:
        description: 'Create a draft release'
        required: true
        type: boolean
        default: true

# set the run-name 
run-name: ${{ github.ref_name }} ->build_create_release (
  ${{ github.run_attempt }}
  )
    
permissions: {}

# Define common environment variables for all jobs
env:
  PLUGIN_NAME: PerplexitySearchShortcut
  DOTNET_VERSION: 9.0.x
  DOTNET_FRAMEWORK: net9.0-windows10.0.22621.0
  DOTNET_NOLOGO: true
  DOTNET_CLI_TELEMETRY_OPTOUT: true

jobs:

  validate:
    name: Validates inputs
    runs-on: ubuntu-latest
    permissions:
      contents: read
    outputs:
      version: ${{ steps.get_version.outputs.version }}
  
    steps:
      - name: Echo current date and time
        id: datetime
        run: |
          echo "datetime: $(date '+%Y-%m-%d %H:%M:%S')"

      - name: Checkout
        uses: actions/checkout@v4
    
      - name: Get version
        id: get_version
        # let's get the version from plugin.json
        run: |
          version=$(jq -r '.Version' plugin.json)
          echo "version is $version"
          echo "version=$version" >> $GITHUB_OUTPUT
      
      #validates that the version is a valid semver
      - name: Validate version
        id: validate_version
        run: |
          if [[ ! ${{ steps.get_version.outputs.version }} =~ ^[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
            echo "Invalid version: ${{ steps.get_version.outputs.version }}"
            exit 1
          fi


  build:
    name: Build
    needs: validate
    strategy:
      matrix:
        platform: [x64, ARM64]
    permissions:
      contents: write
   
    runs-on: windows-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4


      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}

      # Add caching for NuGet packages to speed up builds
      - name: Cache NuGet packages
        uses: actions/cache@v3
        with:
          path: ~/.nuget/packages
          key: ${{ runner.os }}-nuget-${{ hashFiles('**/packages.lock.json', '**/packages.config') }}
          restore-keys: |
            ${{ runner.os }}-nuget-

      - name: Build
        run: dotnet build PowerToys-Run-${{ env.PLUGIN_NAME }}.sln --configuration Release /p:Platform=${{matrix.platform}} /p:EnableWindowsTargeting=true

      - name: List the output files
        run: ls -R 

      - name: Prepare artifact
        run: |
          # Create a temporary directory with the desired structure
          $tempDir = "temp_${{matrix.platform}}"
          $pluginDir = "$tempDir\${{ env.PLUGIN_NAME }}"
          New-Item -Path $pluginDir -ItemType Directory -Force
          
          # Copy files from the target .net framework folder  to our new structure
          Copy-Item -Path "bin\${{matrix.platform}}\Release\${{ env.DOTNET_FRAMEWORK }}\*" -Destination "$pluginDir\" -Recurse

          # Remove unnecessary files
          Remove-Item -Path $pluginDir\* -Recurse -Include *.xml, *.pdb, PowerToys.*, Wox.*
          
      - name: Compress artifact
        run: |
          Compress-Archive -Path "temp_${{matrix.platform}}\${{ env.PLUGIN_NAME }}" -DestinationPath "${{ env.PLUGIN_NAME }}-${{ steps.get_version.outputs.version }}-${{matrix.platform}}.zip"
          
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.PLUGIN_NAME }}-${{ needs.validate.outputs.version }}-${{matrix.platform}}
          path: "${{ env.PLUGIN_NAME }}-${{ needs.validate.outputs.version }}-${{matrix.platform}}.zip"

    
  create_release:
    name: create_release
    runs-on: ubuntu-latest
    needs: [build, validate]
    permissions:
      id-token: write
      contents: write
    steps:

    - name: Checkout
      uses: actions/checkout@v4

      # note: this will download all artifacts to a directory for each artifact
      # https://github.com/actions/download-artifact/tree/v2.1.1/#download-all-artifacts
    - name: Download artifacts
      uses: actions/download-artifact@v4
      with:
        path: dist/
        
    - name: Display structure of downloaded files
      run: ls -R
      working-directory: dist/
    
    - name: Create release branch
      run: |
        git config user.name "GitHub Actions"
        git config user.email "actions@github.com"
        git checkout -b "release/v${{ needs.validate.outputs.version }}"
        git push origin "release/v${{ needs.validate.outputs.version }}"

    - name: Create release through github cli and upload assets
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        gh release create ${{ needs.validate.outputs.version }} --title ${{ needs.validate.outputs.version }} --generate-notes \
          'dist/${{ env.PLUGIN_NAME }}-${{ needs.validate.outputs.version }}-x64/${{ env.PLUGIN_NAME }}-${{ needs.validate.outputs.version }}-x64.zip' \
          'dist/${{ env.PLUGIN_NAME }}-${{ needs.validate.outputs.version }}-ARM64/${{ env.PLUGIN_NAME }}-${{ needs.validate.outputs.version }}-ARM64.zip' \
          ${{ inputs.draft  && '--draft' || '' }}
      